### ISSUE TITLE
Why not put them into a reusable dub package?

### ISSUE THREAD

**Issue by aberba** [joakim-brannstrom/my#1]

**Comment by joakim-brannstrom** [comment]
Yes that is my intention. It is via dub packages I mainly reuse this lib in my own programs.
Is the text in the readme maybe more inviting now? :)

**Comment by aberba** [comment]
Looked through the code. Its seem the ddoc is still work in progress. Documenting the D code itself enables anyone to lookup the Docs and see how things work. Your readme was compelling enough to get me to be interested but I still had to read the code to see what's happening.
